// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	SessionID    int32
	UserID       uuid.UUID
	RefreshToken string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	ExpiresAt    time.Time
}

type User struct {
	UserID    uuid.UUID
	FirstName string
	LastName  sql.NullString
	Email     string
	Phone     string
	Passward  string
	UserType  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ApiKey    string
}
